# .github/actions/common-steps/action.yml
name: "Common Steps"
description: "A set of common steps to reuse in workflows"

runs:
  using: "composite"
  steps:
    - name: Install SFDX
      run: |
           npm -g i @salesforce/cli
      shell: bash

    - name: Install SGD
      run: |
           echo 'y' | sf plugins install sfdx-git-delta
      shell: bash


