# .github/actions/common-steps/action.yml
name: "Common Steps"
description: "A set of common steps to reuse in workflows"

runs:
  using: "composite"
  steps:
    - name: Install SFDX
      run: |
           npm i @salesforce/cli
           echo 'y' | sfdx plugins:install sfdx-git-delta
      shell: bash


