# .github/workflows/build-template.yml
name: build template

on:
  workflow_call:
  
jobs:
  delta:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envname }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Environment set up
        uses: ./.github/actions/common-steps

      - name: Generate Delta Package
        run: |
            mkdir delta-package
            sf sgd:source:delta --from ${{ vars.LAST_COMMIT_ID }} --to "HEAD" --output "delta-package" --generate-delta
        
      - name: Create sfdx-project.json
        run: |
            mv .forceignore.delta delta-package/.forceignore
            cp sfdx-project.json delta-package/

      - uses: actions/upload-artifact@v4
        with:
          name: delta-artifact
          path: delta-package
      
