# .github/workflows/deploy-template.yml
name: deploy template

on:
  workflow_call:
    inputs:
      envname:
        description: 'the name of the environment'
        required: true
        type: string
        default: QA

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.envname }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: environment set up
        uses: ./.github/actions/common-steps

      - name: Print greeting
        run: echo "Hello, ${{ inputs.envname }}!"
      
      - name: Print secret
        run: echo "The secret is ${{ vars.ENV_NAME }}"
