# .github/workflows/develop-deploy.yml
name: Develop - Deployment to QA

on:
  push:
    branches:
      - main

jobs:
  use-reusable-workflow:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'QA'
