# .github/workflows/develop-deploy.yml
name: Develop - Deployment to QA

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'QA'

  deploy-job-2:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'UAT'
