# .github/workflows/develop-deploy.yml
name: Develop - Deployment to QA

on:
  push:
    branches:
      - main

jobs:
  PMD:
    uses: ./.github/workflows/pmd.yml
    
  QA:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'QA'
    needs: PMD

  UAT:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'UAT'
    needs: QA
