# .github/workflows/develop-validate.yml
name: Develop - PR Validation

on:
  workflow_dispatch

jobs:
  PMD:
    uses: ./.github/workflows/pmd.yml
    
  Build:
    uses: ./.github/workflows/build-template.yml
    needs: PMD

  QA:
    uses: ./.github/workflows/validate-template.yml
    with:
      envname: 'QA'
    needs: Build
