# .github/workflows/develop-validate.yml
name: Develop - PR Validation

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'src/**'

jobs:
  PMD:
    uses: ./.github/workflows/pmd.yml
    
  Build:
    uses: ./.github/workflows/build-template.yml
    needs: PMD

  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: Build

    steps:
      - name: validate
        uses: ./.github/workflows/validate-template.yml
        with:
          envname: 'UAT'
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        
