# .github/workflows/develop-deploy.yml
name: Develop - Deployment to QA

on:
  push:
    branches:
      - main

jobs:
  deploy-QA:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'QA'

  deploy-UAT:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'UAT'
    needs: deploy-QA
