# .github/workflows/develop-deploy.yml
name: Develop - Deployment to QA

on:
  push:
    branches:
      - main

jobs:
  QA:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'QA'

  UAT:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'UAT'
    needs: QA
