# .github/workflows/develop-validate.yml
name: Develop - PR Validation

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'src/**'

jobs:
  PMD:
    uses: ./.github/workflows/pmd.yml
    
  Build:
    uses: ./.github/workflows/build-template.yml
    needs: PMD

  QA:
    uses: ./.github/workflows/validate-template.yml
    with:
      envname: 'UAT'
    needs: Build
