# .github/workflows/develop-deploy.yml
name: Develop - Deployment to QA

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'

jobs:
  Build:
    uses: ./.github/workflows/build-template.yml
    
  QA:
    uses: ./.github/workflows/deploy-template.yml
    with:
      envname: 'QA'
    needs: Build
