name: Read Environment Variables
on: 
  workflow_dispatch
jobs:
  read:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
         
      - name: Install SFDX
        run: |
             npm -g i @salesforce/cli
        shell: bash
         
      - name: Read variables
        run: echo ${{ vars.ENV_NAME }}
        shell: bash

      - name: Read serects
        run: |
          echo 'SFDX_AUTH_URL'
          echo $auth_url
        env: 
          auth_url: ${{ secrets.SFDX_AUTH_URL }}
        shell: bash

      - name: Authenticate to ${{ vars.ENV_NAME }}
        run: |
            echo $auth_url > ./authfile
            cat authfile
            sfdx auth:sfdxurl:store -f authfile -a ${{ vars.ENV_NAME }}
        env: 
          auth_url: ${{ secrets.SFDX_AUTH_URL }}
        shell: bash
        
        
