# .github/workflows/release-validate.yml
name: Release - PR Validation

on:
  pull_request:
    branches:
      - release
    paths:
      - 'src/**'

jobs:
  PMD:
    uses: ./.github/workflows/pmd.yml
    
  Build:
    uses: ./.github/workflows/build-template.yml
    needs: PMD

  UAT:
    uses: ./.github/workflows/validate-template.yml
    with:
      envname: 'UAT'
    needs: Build
