# .github/workflows/test.yml
name: TEST YAML

on:
  workflow_dispatch:


jobs:
  Replace:
    uses: ./.github/workflows/string-replace.yml
    with:
      envPath: org-specific/.qa.env
      envname: QA
    secrets:
      AUTH_URL: ${{ secrets.QA_SFDX_AUTH_URL }}
    