name: Update Last Successful Commit Id
on: 
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  analyzer:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           

      - name: Update last commit id 
        run: |
          latest_commit=$(git rev-parse HEAD)
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $gh_token" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Infintura/github-apps/actions/variables/LAST_COMMIT_ID \
            -d '{"name":"LAST_COMMIT_ID","value":"$latest_commit"}'
        env: 
          gh_token: ${{ secrets.GH_TOKEN }}
